import { Metadata } from 'next';
import Link from 'next/link';
import { getTodo, Todo } from '@/lib/todos';

type Params = { params: { todoId: number } };

export const revalidate = 5;

// export const metadata: Metadata = {
//   title: 'Todo',
//   description: 'Generated by create next app',
// };

export async function generateMetadata({
  params: { todoId },
}: Params): Promise<Metadata> {
  const todo: Todo = await getTodo(+todoId);
  return {
    title: `ToDo - ${todo.title}`,
  };
}

export default async function Todo({ params: { todoId } }: Params) {
  const { title, completed } = await getTodo(+todoId);
  console.log('Todo - todo - id:', todoId); // dynamic test ISR
  if (!title) {
    // return <h1 className='text2xl text-red-500'>#{todoId} is not found !!</h1>;
    throw new Error(`#${todoId} is not found !!`);
  }

  return (
    <div className='text-left'>
      <div>id: {todoId}</div>
      <div>title: {title}</div>
      <div>completed: {completed ? 'Done' : 'Doing...'}</div>
      <Link href='/todos'>Go Back</Link>
    </div>
  );
}
